// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStructure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateStructure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function ListFolders(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListFolders'](arg1, arg2, arg3, arg4);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}
