// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateStructure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<Array<string>>;

export function GetPassword(arg1:string):Promise<string>;

export function ListFolders(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveCredentials(arg1:string,arg2:string):Promise<void>;
